language: node_js
node_js:
  - '6'
sudo: required
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn install
script:
  - yarn unit
services:
  - docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=rdpanek/monitor
after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - export REPO=$DOCKER_USER/monitor
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker build -t $REPO:$TAG-$COMMIT -f Dockerfile .
  - docker push $REPO
notifications:
  slack:
    rooms:
      secure: oQeG2hSL+jVOtYAyHHCK+aYhRg5GbgBmuilHrfOIDYmFHh508DlPD0bkCuU2GlwOrVeEXaxBrb63Xj4/EV3Bu4efGhg5wyhiZxy4mlolfIU0h7nLHck65MUJzYYpM6B455yWkqdjbnrBfDmmV20lHKx8kvFYOO0wO+0GzPpnxHEsFjppBDUOCg2QbKFx/b8HEzK/yAvDrAyKRM+fA03d5H/jNXfLe8zuY2xrDOikaFMSyaO9GikqLeR5RYk5hQHDhotQU14povyZo+p15P/pGC6mD7rsytaLY4cf+7RSLCbKqF25gsVmzMAdRmgGkeoAY0WLzAXYJbM+CIKIfb+VtjoH7CcfVo4kJhy4ynMCVA+vfuIcl1cjTu4U2+kCZ9zrO9l9+dTXw+Dg+t8xwhbf1DlmzGoS8Pd154ZfVOWjRtI3UUAO69jJwMydIkhAqJo2fYyLHLtWFrC1nwMvp41j7DVDi478Eoa2EpURZREuTf5JcqWcH55a2Kb6Cb2jmDJJrHv+jGRxSrhAOTtp/gTAYyGjevj/03M8O0ai9S5jHaZAvS+Hy8hVEnXTEtr+IgYEusGvEiALIbxZIu9uIjj0f9rj2OO41g0/Ye+BTRWoiEdvVVsgA8HEVUhsTrZZlRKPswFnGh7mKF7HvWp2GLd0REOHooZVUmk9jSUCaZpQju8=
    on_success: always
    template:
    - "%{repository} (%{commit}) : %{commit_subject} | %{commit_message} "
    - 'Build details: %{build_url}'
    - Build <%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
      by %{author} %{result} in %{duration}
