kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: monitor
  labels:
    component: monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: monitor
    spec:
      serviceAccount: monitor
      containers:
      - name: monitor
        image: rdpanek/monitor:0.1.0
        imagePullPolicy: Always
        env:
        - name: ELASTIC_URI
          value: "http://tea.comm.equabank.loc:9200"
        resources:
          requests:
            memory: 100Mi
            cpu: 0.5
          limits:
            memory: 400Mi
            cpu: 1
        ports:
        - containerPort: 3000
          name: client
          protocol: TCP
        - containerPort: 3001
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 20
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: monitor
  labels:
    component: monitor
spec:
  type: NodePort
  selector:
    component: monitor
  ports:
  - name: http
    port: 3000
    nodePort: 32695
    protocol: TCP
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: monitor
