export const TOGGLE_SLOT_DIALOG = "TOGGLE_SLOT_DIALOG";
export const PROGRESS_SLOT_DIALOG_SUCESS = "PROGRESS_SLOT_DIALOG_SUCESS";
export const PROGRESS_SLOT_DIALOG_FAILED = "PROGRESS_SLOT_DIALOG_FAILED";
export const PROGRESS_SLOT_DIALOG_RESET = "PROGRESS_SLOT_DIALOG_RESET";
export const PROGRESS_SLOT_DIALOG_WAIT = "PROGRESS_SLOT_DIALOG_WAIT";
export const FETCH_SLOTS_FROM_SERVER = "FETCH_SLOTS_FROM_SERVER";
export const SELECT_SLOT_BY_ID = "SELECT_SLOT_BY_ID";
